### ISSUE TITLE
Feature Request: Brightness Profile Defaults or Presets

### ISSUE THREAD

**Issue by PProvost** [finity69x2/light-brightness-preset-row#17]
I'd love to be able to set a global configuration to define what Low/Med/High mean. Many of my lights are LED bulbs, and for those, I'd like to use a different set of levels without having to copy paste it into each entity in the card.

An alternative might be to allow profiles. Then maybe I could do this:

````yaml
cards:
    - type: entities
      title: Hall Light Presets
      show_header_toggle: false
      entities:
        - entity: light.hall_light
          type: custom:light-brightness-preset-row
          level_profile: my_led_profile
````

Thanks for the great card!
