### ISSUE TITLE
Custom setpoints not working

### ISSUE THREAD

**Issue by mdezzi** [finity69x2/light-brightness-preset-row#21]
I have noticed that the custom setpoints that i have set don't seem to be triggering light light to the same brightness. Here's my code: 

```
entities:
  - HiBrightness: 255
    LowBrightness: 85
    MedBrightness: 125
    customSetpoints: true
    entity: light.fireplace_lights
    type: 'custom:light-brightness-preset-row'
```

When i click each button, the light changes to the following brightnesses:
High: 214
Med: 130
Low: 46
