### ISSUE TITLE
sample cfg from repo are not in HACS

### ISSUE THREAD

**Issue by thefrenchmatt** [finity69x2/light-brightness-preset-row#5]
Not really an issue and more an observation, users will expect to find at least 1 or 2 examples in HACS :) I just came over to say thanks for sharing it with the community. M

**Comment by thefrenchmatt** [comment]
You can also delete the first "cards:", it's not needed in lovelace.

Instead of the preview, users will get an error :/

I removed the extra indentation & it's working perfectly and up to expectations, nice work!

```
type: entities
title: Hall Light Presets
show_header_toggle: false
entities:
## USE THIS CONFIG TO HAVE IT MATCH YOUR THEME ##
- entity: light.XXXXXXXXXX
  type: custom:light-brightness-preset-row
  name: Light Not Custom Theme
  customTheme: false
## USE THIS CONFIG TO USE A DEFAULT CUSTOM THEME
- entity: light.XXXXXXXXXX
  type: custom:light-brightness-preset-row
  name: Light Default Custom Theme
  customTheme: true
  customSetpoints: true
  LowBrightness: 30
  MedBrightness: 100
  HiBrightness: 225
## USE THIS CONFIG TO USE A 'CUSTOMZED' CUSTOM THEME
- entity: light.XXXXXXXXXX
  type: custom:light-brightness-preset-row
  name: Light Custom Custom Theme
  customTheme: true
  IsOnLowColor: 'rgb(255, 0, 0)'
  IsOnMedColor: '#888888'
  IsOnHiColor: '#222222'
  ButtonInactiveColor: '#aaaaaa'
  IsOffColor: 'purple'


```
