### ISSUE TITLE
Button background not changed if entity is group

### ISSUE THREAD

**Issue by nigotiator** [finity69x2/light-brightness-preset-row#7]
Thanks for the great plugin!
If I want to control the light group it seems that button background is not changed correctly. Consider this setup.
```
type: entities
title: Valot
show_header_toggle: false
entities:
  - entity: group.olohuone
    type: 'custom:light-brightness-preset-row'
    name: Olohuone
    customTheme: true
    customSetpoints: true
    LowBrightness: 30
    MedBrightness: 125
    HiBrightness: 255
    IsOnLowColor: '#ffffe6'
    IsOnMedColor: '#ffff99'
    IsOnHiColor: '#ffff00'
    ButtonInactiveColor: '#f2f2f2'
    IsOffColor: '#ffcccc'
  - entity: light.oh_kruunu
    type: 'custom:light-brightness-preset-row'
    name: Kruunu
    customTheme: true
    customSetpoints: true
    LowBrightness: 30
    MedBrightness: 125
    HiBrightness: 255
    IsOnLowColor: '#ffffe6'
    IsOnMedColor: '#ffff99'
    IsOnHiColor: '#ffff00'
    ButtonInactiveColor: '#f2f2f2'
    IsOffColor: '#ffcccc'
```
Entity `light.oh_kruunu` is part of the group `group.olohuone`
So in the screenshot I have clicked the `Olohuone > HIGH` and the `Kruunu > HIGH` has the correct yellow background but the Olohuone group is all grayed out.
![card](https://user-images.githubusercontent.com/477138/72787528-c938cf00-3c38-11ea-8ce8-ccdcdda3e898.png)
